[package]
name = "encoder_decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
powerpack = "0.2.1"
base64 = "0.13.0"

[[bin]]
name = "encoder"

[[bin]]
name = "decoder"
